### ISSUE TITLE
Many images on the website don't load

### ISSUE THREAD

**Issue by jvanderloo** [UIGuideline/UIGuideline#2]
**Describe the bug**
When browsing the website https://www.uiguideline.com/ many images (notably all the component images) don't load.

When looking at the network panel in my browser's dev tools I can see that they are being requested from Request URL: `https://firebasestorage.googleapis.com/` but return a HTTP 402.

**To Reproduce**
1. Go to 'www.uiguideline.com'
4. See images not loaded

**Expected behavior**
Images detailing the various components are shown in the initial grid

**Screenshots**

![Screenshot of the homepage on uiguideline.com showing a grid of components but no images detailing the components](https://user-images.githubusercontent.com/53157951/88603324-e652cc80-d0b7-11ea-98d0-18a5a9e76f6d.png)

![Screenshot of the select dropdown page on uiguideline.com showing some broken images and no images detailing the component](https://user-images.githubusercontent.com/53157951/88603402-27e37780-d0b8-11ea-93bf-bd1dc1f96ff3.png)

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser Chrome, Firefox

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy
 - OS: Android 10
 - Browser: Chrome

**Comment by sruda** [comment]
@jvanderloo Yes, it was a funny thing the last week, because that day was the first day UI Guideline had high traffic, so we consumed all the daily free quotes from our current image hosting provider (firebase) 😅.
So, we're discussing which other options could be better to host our images.

Thanks for reporting it.
