### ISSUE TITLE
Get ERROR when enter the website

### ISSUE THREAD

**Issue by ArnonChonrawut** [UIGuideline/UIGuideline#8]
**Describe the bug**
Get error message when enter the website

**To Reproduce**
1. Go to 'https://www.uiguideline.com/components'
4. See error message in content

**Expected behavior**
See the website content

**Screenshots**
![Screenshot 2565-12-10 at 21 20 50](https://user-images.githubusercontent.com/115442516/206860037-06244574-118e-4395-a111-3bc892a49f5b.png)

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.0.1
 - Browser: Brave
 - Version:  1.46.140

**Comment by navaru** [comment]
Appears to be a CORS issue:

```
Access to fetch at 'https://ui-guideline-server-production.herokuapp.com/v1/graphql'
from origin 'https://www.uiguideline.com' has been blocked by CORS policy: Response
to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin'
header is present on the requested resource. If an opaque response serves your needs,
set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by seb-giroux** [comment]
@sruda Any feedback on this issue? The site is unusable in its current state. Thanks!

**Comment by serudda** [comment]
Hi, I'm checking the issue. I'll be working on it throughout the day. Thanks for reporting it.

**Comment by serudda** [comment]
I was looking for the issue, and I think it is something related with Heroku plan... I don't know why they detached the Database from the ui-guideline-app. Researching a bit, I figured out it could happen when they have a maintenance windows... the wire thing is that generally this windows just last 48 hours... we have the app down 3 days.

I've already created a ticket... so for now, we just need to wait for a response.

![image](https://user-images.githubusercontent.com/10075532/207411410-53535be2-8032-471e-a1f9-c4b39dd13b29.png)

This is the current issue, if someone knows more about it, please let me know if there's a solution from our site without wating for a Heroku's response.

![Screenshot 2022-12-13 at 1 09 01 PM](https://user-images.githubusercontent.com/10075532/207411866-21822d95-6ced-4871-9c30-70442015eebf.png)

**Comment by HamidDjangi** [comment]
Is there an update on this? It's been a few weeks since the site went down.

**Comment by serudda** [comment]
@HamidDjangi the site is up again... the idea is open it during this month in order to give you access to all the completed components... we want to transform this project to an open-source one.
